<?php

$languages = array(
    'title' => 'Tiêu đề',
    'return' => 'Trở lại',
    'dateline' => 'Thời gian',
    'delete' => 'Xóa',
    'checkall' => 'Chọn hết',
    'submit' => 'Submit',
    'yes' => 'Yes',
    'no' => 'No',
    'tips' => 'Gợi ý',
    'list_empty' => 'Tạm thời chưa có danh sách ghi chép nào!',
    'shortcut_tips' => 'Bấm vào chỉnh sửa rồi mới bấm submit để sao lưu',
    'welcome' => 'Chào bạn ',
    'edit' => 'Sửa',
    'plugin' => 'Plugin',
    'to' => 'Tới',
    'menu' => 'Menu',
    'founder' => 'Người sáng lập',
    'login_username' => 'Tên',
    'login_password' => 'Mật khẩu',
    'login_submit' => 'Đăng nhập',
    'login_seccode' => 'Code',
    'login_incorrect' =>
        '<em>Đăng nhập thất bại!</em><br />Tên thành viên hoặc mật khẩu không đúng.',
    'login_founder_incorrect' => 'Mật khẩu người sáng lập không hợp lệ',
    'login_admin_noexists' => 'Người Quản lý này không tồn tại',
    'login_seccode_error' => 'Mã nghiệm chứng sai',
    'login_failedlogin' => 'Mật khẩu nhập sai nhiều lần, 15 phút sau thử lại',
    'login_tips' =>
        'UCenter là một ứng dụng cầu nối, nó có thể chia sẻ dữ liệu thành viên, đồng nhất đăng nhập, đăng ký và quản lý thành viên.',
    'login_seccode_tips' =>
        'Nếu bạn không thấy rõ mã nghiệm chứng xin đổi mã khác',
    'login_secques' => 'Câu hỏi bảo mật',
    'login_remove_secques' => 'Xóa câu hỏi bảo mật',
    'login_getpw' => 'Lấy lại mật khẩu',
    'menu_index' => 'Trang chủ',
    'menu_basic_setting' => 'Cơ bản',
    'menu_register_setting' => 'Register Config',
    'menu_mail_setting' => 'Thiết lập Mail',
    'menu_manager_user' => 'User Manager',
    'menu_pm' => 'Tin hệ thống',
    'menu_credit_exchange' => 'Đổi điểm',
    'menu_censor_word' => 'Bộ lọc từ cấm',
    'menu_application' => 'Quản lý ứng dụng',
    'menu_data_list' => 'Data list',
    'menu_domain_list' => 'Domain list',
    'menu_db' => 'Data backup',
    'menu_update_cache' => 'Update cache',
    'menu_log' => 'LOG Manager',
    'menu_logout' => 'Thoát',
    'menu_otheradmincp' => 'Quản lý khác',
    'menu_admin_user' => 'Admin list',
    'pm_from' => 'Người gửi',
    'pm_to' => 'Người nhận',
    'pm_none_record' => 'Chưa có tin nhắn nào',
    'pm_total_pm' => 'Bạn có $pmnum[$pmnumindex] 5 tin nhắn',
    'pm_system_pm' => 'Tin nhắn từ hệ thống',
    'pm_ignore_list' => 'Danh sách từ chối',
    'pm_ignore_list_comment' =>
        'Nếu bạn thêm thành viên nào đó vào danh sách này, thì bạn sẽ không nhận bất cứ thông tin nào từ thành viên này<br />Nhiều hơn một người xin mời dùng dấu phẩy ngăn cách<br />Nếu như không muốn nhận tin nhắn xin mời bấm "&#123;ALL&#125;"',
    'save' => 'Lưu',
    'pm_central' => 'Hòm tin',
    'pm_send' => 'Gửi tin nhắn',
    'pm_send_announce' => 'Gửi tin thông báo',
    'pm_unread' => ' tin chưa đọc',
    'pm_history' => 'Danh sách tin báo',
    'pm_sysbox' => ' tin thông báo',
    'pm_annbox' => 'Tin nhắn thông báo',
    'pm_savebox' => 'Thư nháp',
    'pm_outbox' => 'Thư đến',
    'pm_ignorelist' => 'Danh sách từ chối',
    'pm_preview' => 'Xem trước tin nhắn',
    'back' => 'Trở lại',
    'pm_tofriends' => 'Bạn',
    'pm_subject' => 'Tiêu đề',
    'pm_notitle' => '[Không tiêu đề]',
    'pm_message' => 'Nội dung tin',
    'pm_replymessage' => 'Nội dung trả lời',
    'pm_sendpm' => 'Gửi',
    'pm_recv' => 'Người nhận',
    'pm_transmit' => 'Chuyển',
    'pm_mark_unread' => 'Đánh dấu chưa đọc',
    'pm_swith_friendls' => 'Mở/Đóng danh sách bạn',
    'reply' => 'Trả lời',
    'upload' => 'Upload',
    'pm_inbox' => 'Thư nhận',
    'pm_inboxnew' => 'Hòm thư có ',
    'pm_current' => 'Tin nhắn ngắn hiện tại',
    'pm_system' => 'Thông tin hệ thống',
    'pm_preview' => 'Xem trước tin nhắn',
    'pm_date' => 'Thời gian',
    'pm_daterange_1' => 'Hôm nay',
    'pm_daterange_2' => 'Hôm qua',
    'pm_daterange_3' => 'Hôm trước',
    'pm_daterange_4' => 'Tuần trước',
    'pm_daterange_5' => 'Lâu lắm rồi',
    'pm_prompt_list' => 'Nhập danh sách.\\r\\nĐể trống hoặc bỏ để hoàn thành.',
    'pm_prompt_img' => 'Xin mời nhập liên kết hình:',
    'pm_prompt_url' => 'Xin mời nhập liên kết:',
    'pm_prompt_email' => 'Xin mời nhập email:',
    'pm_confirm_delete' => 'Bạn có chắc chắn muốn xóa tất cả các tin nhắn SMS?',
    'pm_delete_all' => 'Xóa tất cả',
    'pm_delete_chatpm' => 'Xóa nhóm chat',
    'pm_quit_chatpm' => 'Thoát khỏi trò chuyện nhóm',
    'pm_confirm_deletechatpm' => 'Bạn có chắc muốn xóa nhóm trò chuyện?',
    'pm_confirm_quitchatpm' => 'Bạn có chắc muốn thoát khỏi nhóm chat?',
    'new_pm' => 'Tin mới',
    'private_pm' => 'Tin riêng',
    'chat_pm' => 'Nhóm tin nhắn chat',
    'pm_member' => 'Thành viên tham gia',
    'pm_confirm_kickmember' => 'Bạn có chắc chắn muốn kick người?',
    'kickmember' => 'Đuổi ra khỏi',
    'appendchatpmmember' => 'Thành viên mới',
    'appendmember' => 'Tham gia',
    'tipkickmember' => 'đã {$member} kích bạn ra khỏi nhóm',
    'pm_author' => 'Người lập nhóm',
    'sendto' => 'Gửi đến: ',
    'fromto' => 'Từ: ',
    'sendeveryone' => 'Gửi đến tất cả',
    'privatewithwho' => 'Và $pm[tousername] đối thoại',
    'chatpmmembernum' => 'Số người tham gia: ',
    'chatpm' => 'Trò chuyện nhóm',
    'editor_b' => 'Đậm',
    'editor_i' => 'Nghiêng',
    'editor_u' => 'Gạch dưới',
    'editor_list1' => 'Sắp xếp',
    'editor_lista' => 'Chưa sắp xếp',
    'editor_indent' => 'Thêm thụt vào',
    'editor_color' => 'Màu sắc',
    'editor_alignleft' => 'Căn trái',
    'editor_aligncenter' => 'Căn giữa',
    'editor_alignright' => 'Căn phải',
    'editor_floatleft' => 'Float left',
    'editor_floatright' => 'Float right',
    'editor_code' => 'Code',
    'editor_quote' => 'Quote',
    'editor_img' => 'IMG',
    'editor_url' => 'URL',
    'editor_email' => 'EMAIL',
    'app_list' => 'Danh sách ứng dụng',
    'app_list_updated' => 'Cập nhật thành công ứng dụng.',
    'app_list_return' => 'Trở lại danh sách ứng dụng',
    'app_list_tips' =>
        'Nếu như bạn phát hiện <img src="images/error.gif" /> <font color="red">kết nối thất bại</font>, xin mời bấm sửa lại tên miền hoặc IP.',
    'app_add' => '＋thêm ứng dụng',
    'app_add_succeed' => 'Thêm ứng dụng thành công',
    'app_delete' => 'Xóa',
    'app_id' => 'ID',
    'app_name' => 'Tên ứng dụng',
    'app_name_comment' => 'Tên ứng dụng không quá 20 ký tự',
    'app_url' => 'URL liên kết',
    'app_url_comment' =>
        'Đây là cổng nối giữa UCenter với ứng dụng khác, cuối link không thêm dấu /',
    'app_extra_url' => 'URL các ứng dụng khác ',
    'app_extra_url_comment' =>
        'Đây là cổng nối giữa UCenter với ứng dụng khác, cuối link không thêm dấu /',
    'app_ip' => 'IP ứng dụng',
    'app_ip_comment' =>
        'Ở trạng thái bình thường bạn không có vấn đề gì với việc nhập với tên miền, nếu như nhập tên miền có lỗi xin mời bạn thử nhập IP của máy chủ bạn.',
    'app_key' => 'Key',
    'app_key_comment' =>
        'Chỉ được sử dụng ký tự tiếng anh và được dùng dưới 64 ký tự, key của ứng dụng phải cùng với Ucenter giống nhau, nếu không dữ liệu ứng dụng với Ucenter không hoạt động bình thường',
    'app_login' => 'Đồng bộ đăng nhập',
    'app_login_comment' =>
        'Khởi động chức năng này, khi bạn đăng nhập ở Ứng dụng thì bạn không cần đăng nhập ở diễn đàn',
    'app_charset' => 'Charset',
    'app_dbcharset' => 'Database charset',
    'app_detail' => 'Chi tiết',
    'app_detail_tips' =>
        'Nếu như bạn phát hiện <img src="images/error.gif" /> <font color="red"> không thể kết nối</font>, xin mời chỉnh sửa tên miền hoặc IP thích hợp',
    'app_edit' => 'Sửa',
    'app_setting' => 'Sửa ứng dụng',
    'app_type' => 'Loại ứng dụng',
    'app_linkstatus' => 'Trạng thái',
    'app_link' => 'Đang kết nối...',
    'app_recvnote' => 'Nhận thông báo',
    'app_tagtemplates' => 'Nhãn hiển thị tại giao diện',
    'app_tagtemplates_comment' => 'Sử dụng dữ liệu nhãn tại giao diện khác',
    'app_tagfields' => 'Giao diện nhãn',
    'app_tagfields_comment' =>
        'Mỗi dòng một cách gợi ý nhãn, dùng dấu phẩy để phân cách giữa nhãn và gợi ý',
    'app_install_type' => 'Chọn cách cài',
    'app_install_url' => 'Địa chỉ cài',
    'app_install_by_url' => 'URL cài',
    'app_install_by_custom' => 'Tự cài',
    'app_install_submit' => ' Cài đặt ',
    'app_path' => 'Đường dẫn vật lý của ứng dụng',
    'app_path_comment' =>
        'Vui lòng trống mặc định, nếu như để điền vào đường dẫn liên quan (như ngược với UC), thủ tục sẽ tự động được chuyển đổi sang một con đường tuyệt đối, chẳng hạn như ../',
    'app_viewpro_url' => 'Xem các dữ liệu cá nhân',
    'app_viewpro_url_comment' =>
        ' Đại chỉ URL,thay cho：/space.php?uid=%s bằng %s uid',
    'app_api_filename' => 'Ứng dụng giao diện tên tập tin',
    'app_api_filename_comment' =>
        'Ứng dụng giao diện tập tin tên, theo mặc định uc.php',
    'app_code' => 'Áp dụng UCenter cấu hình thông tin',
    'app_code_comment' =>
        'Khi các ứng dụng UCenter thông tin cấu hình có thể được sao chép vào các ứng dụng mã ở phía bên trái của các hồ sơ',
    'app_not_add_tips' =>
        '不能通过 URL 添加应用的可能原因：1. 通过 URL 添加应用开关被关闭；2. 连续多次错误输入 UCenter 创始人密码',
    'tag_tips' =>
        'Thiết lập ứng dụng hiện tại để thu hút TAG của ứng dụng khác. Trong giao diện "&#123;xxx&#125;" có nghĩa là đã lấy dữ liệu TAG biểu thị tương ứng tương đồng dữ liệu',
    'tag_global_template' => 'Giao diện chung',
    'tag_percent' => 'Ví dụ',
    'tag_template' => 'Giao diện',
    'tag_edit' => 'Biên tập',
    'tag_template_comment' => 'Bao gồm dữ liệu giao diện đơn',
    'badword_list' => 'Từ cấm',
    'badword_list_updated' => 'Cập nhật từ cấm thành công',
    'badword_add' => 'Thêm từ cấm',
    'badword_add_succeed' => 'Thêm từ cấm thành công',
    'badword_delete' => 'Xóa',
    'badword_keyword' => 'Từ nhạy cảm',
    'badword_replace' => 'Thay bằng',
    'badword_admin' => 'Thực thi',
    'badword_multi_add' => 'Thêm hàng loạt',
    'badword_multi_add_comment' => '<li>Những từ cấm của diễn đàn.</li>
					<li>If you want to replace a word directly **, just type the words can be</li>
					<li><strong>Ví dụ：</strong></li>
					<li>toobad</li>
					<li>badword=good</li>',
    'badword_skip' => 'Trong lúc hoạt động, bạn có thể bỏ để quay lại từ đầu',
    'badword_overwrite' => 'Trong lúc xung đột, đè lên từ cấm cũ',
    'badword_truncate' =>
        'Dọn sạch từ cấm trước, nhập từ cấm mới, hành động này bạn có thể sao lưu tại <a href="admin.php?m=badword&a=export" target="_blanks">đây</a>',
    'announcepm' => 'Quản lý Tin hệ thống',
    'announcepm_deleted' => 'Xóa thành công tin nhắn công cộng',
    'clear_pm' => 'Dọn sạch tin nhắn',
    'clearpm_deleted' => 'Dọn thành công tin nhắn',
    'clearpm_totalnum' => 'Tổng số tin nhắn',
    'clearpm_delunread' => 'Không xóa chưa dọc',
    'clearpm_cleardays' => 'Xóa tin trước mấy ngày',
    'clearpm_cleardays_comment' => 'Không hạn chế chọn 0',
    'clearpm_usernames' => 'Xóa của một của người dùng viết tắt Nội dung',
    'clearpm_usernames_comment' => 'Nhập tên thành viên',
    'announcepm_send_succeed' => 'Tin nhắn công cộng gửi thành công',
    'pm_clear' => 'Xóa tin nhắn',
    'pm_search' => 'Tìm tin nhắn',
    'pm_whichtable' => 'Chọn chi tiết',
    'pm_auhtor' => 'Người gửi',
    'pm_dateline' => 'Thời gian ',
    'pm_list' => 'Danh sách tin nhắn',
    'pm_delete_confirm' => 'Bạn muốn xóa hết tin nhắn, sẽ không hồi phục được?',
    'creditexchange_updated' => 'cập nhật các chương trình nhập thành công',
    'creditexchange_invalid' =>
        'Trao đổi trước và sau khi áp dụng cùng một, xin vui lòng thiết lập lại.',
    'creditexchange_update' => 'Thông tin giao dịch Điểm thưởng',
    'creditexchange_fromto' => 'Từ loại',
    'creditexchange_select' => 'Xin vui lòng lựa chọn',
    'creditexchange_ratio' => 'Tỷ lệ',
    'creditexchange' => 'Trao đổi Điểm thưởng ',
    'creditexchange_syncappcredits' =>
        'Áp dụng đồng thời cho các thiết lập điểm',
    'creditexchange_tips' =>
        'Bấm vào [đồng thời áp dụng các thiết lập điểm] có thể được áp dụng để có được những thiết lập điểm, và thiết lập để thông báo các kết quả của ứng dụng',
    'note_deleteuser' => 'Xóa thành viên',
    'note_deletefriend' => 'Xóa bằng hữu',
    'note_gettag' => 'TAG',
    'note_updateclient' => 'Cập nhật Cache ứng dụng',
    'note_list' => 'Danh sách thông báo',
    'note_list_updated' => 'Danh sách thông báo cập nhật thành công',
    'note_test' => 'Test',
    'note_delete' => 'Xóa',
    'note_operation' => 'Thao tác',
    'note_times' => 'Số lần',
    'note_param' => 'Tham số',
    'note_last_note_time' => 'Thông báo cuối',
    'note_view' => 'Xem',
    'setting_forbidden_username' => 'Cấm thành viên',
    'setting_ceonsor_comment' => 'Có thể thiết đặt thêm dấu sao, vd: beauty*',
    'note_view' => 'Xem',
    'note_status' => 'Thông báo trạng thái',
    'note_fail_apps' => 'Áp dụng việc thông báo',
    'feed_list' => 'Danh sách các sự kiện',
    'tag_list' => 'Danh sách nhãn',
    'mail_queue' => 'E-mail queue',
    'mail_delete' => 'Loại bỏ',
    'mail_subject' => 'Tiêu đề',
    'mail_to_username' => 'Tên',
    'mail_add_time' => 'Thời gian',
    'mail_failures' => 'Không thành công',
    'mail_from_app' => 'Nguồn',
    'mail_operate' => 'Hoạt động',
    'anonymity' => 'Chưa xác định người gởi',
    'mail_send' => 'Gửi e-mail',
    'mail_list_updated' => 'Cập nhật danh sách',
    'mail_send' => 'Gửi e-mail',
    'setting' => 'Thiết lập',
    'setting_tips' => '',
    'setting_dateformat' => 'Dạng ngày tháng',
    'setting_dateformat_comment' =>
        'Sử dụng yyyy(yy): năm, mm tháng, dd ngày. Ví dụ dd-mm-yyyy biểu thị 2000-1-1',
    'setting_timeformat' => 'Dạng thời gian',
    'setting_timeformat_hr24' => '24h',
    'setting_timeformat_hr12' => '12h',
    'setting_timeoffset' => 'Khu vực',
    'setting_timeoffset_comment' => 'Mặc định: GMT +08:00',
    'setting_pmsendregdays' => 'đăng ký ít nhất một vài ngày',
    'setting_pmsendregdays_comment' =>
        'Đăng ký lần ít hơn các thiết lập số ngày, không được cho phép để gửi tin nhắn ngắn, một di chuyển được thực hiện theo thứ tự để hạn chế tự động quảng cáo',
    'setting_pmcenter' => 'Mở cửa của Trung tâm tin nhắn ngắn',
    'setting_pmcenter_comment' =>
        'Dù là việc khai trương của Trung tâm tin nhắn ngắn tính năng sẽ không ảnh hưởng đến việc sử dụng các ứng dụng tin nhắn SMS để sử dụng giao diện',
    'setting_sendpmseccode' => 'Mã xác minh',
    'setting_sendpmseccode_comment' =>
        'Mã xác thực, để ngăn mã độc hại đến hệ thống',
    'setting_privatepmthreadlimit' =>
        'The same user within 24 hours to allow the maximum number of sessions initiated by two',
    'setting_privatepmthreadlimit_comment' =>
        'The same user within 24 hours, two sessions can be initiated by the maximum recommended 30 - 100 range of values, 0 for no restrictions, a move made to limit the quantities of advertising through the machine',
    'setting_chatpmthreadlimit' => 'Phiên chat của một người trong 24h',
    'setting_chatpmthreadlimit_comment' =>
        'Cùng một người sử dụng có thể được bắt đầu trong vòng 24 giờ đồng hồ tối đa của nhóm phiên chat, đã đề nghị 30-100 phạm vi giá trị, 0 để không có giới hạn, một động thái để hạn chế số lượng quảng cáo được gửi qua số lượng máy',
    'setting_chatpmmemberlimit' => 'Tham gia chat với số người lớn nhất',
    'setting_chatpmmemberlimit_comment' =>
        'Cùng một phiên có thể có đến tham gia thiết lập số lượng người dùng, chúng tôi đề nghị 30-100 phạm vi giá trị, 0 để không có giới hạn',
    'setting_pmfloodctrl' => 'prevent water',
    'setting_pmfloodctrl_comment' =>
        '0 không có hạn chế về việc di chuyển để giới hạn các máy móc thông qua hàng loạt quảng cáo',
    'setting_addappbyurl' => '启用通过 URL 添加应用功能',
    'setting_addappbyurl_comment' =>
        '是否启用通过 URL 添加应用功能，建议只有必须通过 URL 添加应用时开启',
    'setting_user_failedtime' => '允许用户登录失败次数',
    'setting_user_failedtime_comment' =>
        '用户登录失败超过设置的次数，将在 15 分钟内无法登录，0 为使用默认设置，负数为不限制次数（不安全）',
    'setting_register' => 'Thiết lập đăng ký',
    'setting_register_tips' =>
        'Cho phép/ Cấm Email, mỗi dòng một cái email, ví dụ @hotmail.com',
    'setting_register_doublee' => 'Cho phép nhiều tài khoản đăng ký một email',
    'setting_register_accessemail' => 'Email cho phép',
    'setting_register_accessemail_comment' =>
        'Chỉ cho phép email này đăng ký trên diễn đàn',
    'setting_register_censoremail' => 'Cấm Email',
    'setting_register_censoremail_comment' =>
        'Cấm sử dụng email có đuôi tên miền để đăng ký',
    'settings_mail_settings_emailfrom' => 'Địa chỉ E-mail của các nguồn',
    'settings_mail_settings_emailfrom_comment' =>
        'Gửi e-mail khi bạn không chỉ rõ nguồn gốc của e-mail, sử dụng mặc định địa chỉ e-mail như là một nguồn',
    'settings_mail_settings_silent' => 'Khảo sát của tất cả các thư gửi lỗi',
    'settings_mail_settings_send' => 'Gửi e-mail',
    'settings_mail_settings_send_1' =>
        'Thông qua PHP để sendmail (Đề nghị nên dùng)',
    'settings_mail_settings_send_2' =>
        'Thông qua SOCKET Kết nối máy chủ SMTP để gửi(Phải hỗ trọ ESMTP)',
    'settings_mail_settings_send_3' =>
        'PHP thông qua chức năng SMTP để gửi email (chỉ dưới Windows máy chủ hiệu quả và không hỗ trợ ESMTP xác thực)',
    'settings_mail_settings_server' => 'SMTP Server',
    'settings_mail_settings_server_comment' =>
        'Thiết lập các địa chỉ máy chủ SMTP',
    'settings_mail_settings_port' => 'Cổng SMTP',
    'settings_mail_settings_port_comment' =>
        'Thiết lập cổng máy chủ SMTP , mặc định là 25',
    'settings_mail_settings_auth' => 'SMTP Phục vụ yêu cầu xác thực',
    'settings_mail_settings_auth_comment' =>
        'Nếu các máy chủ SMTP cần xác thực trước khi họ có thể gửi thư, chọn "Có"',
    'settings_mail_settings_from' => 'Địa chỉ E-mail của người gửi',
    'settings_mail_settings_from_comment' =>
        'Nếu bạn cần xác minh, để được phục vụ dựa trên địa chỉ e-mail. Địa chỉ E-mail nếu bạn muốn bao gồm một người dùng tên, định dạng「username &lt;user@domain.com&gt;」',
    'settings_mail_settings_username' => 'SMTP Xác thực tên người dùng',
    'settings_mail_settings_password' => 'SMTP Xác nhận mật khẩu',
    'settings_mail_settings_delimiter' => 'Đầu tiên e-mail',
    'settings_mail_settings_delimiter_comment' =>
        'Tùy thuộc vào cài đặt máy chủ thư của bạn để điều chỉnh các tham số',
    'settings_mail_settings_delimiter_crlf' =>
        'CRLF được sử dụng như một separator',
    'settings_mail_settings_delimiter_lf' =>
        'LF được sử dụng như một separator',
    'settings_mail_settings_delimiter_cr' =>
        'CR được sử dụng như một separator',
    'settings_mail_settings_includeuser' => 'Địa chỉ người nhận',
    'settings_mail_settings_includeuser_comment' =>
        'Chọn "Có" của người nhận ở địa chỉ e-mail bao gồm trong diễn đàn để hiện tên thành viên',
    'domain_list' => 'Danh sách tên miền',
    'domain_list_updated' => 'Cập nhật tên miền thành công',
    'domain_add' => 'Thêm tên miền',
    'domain_add_succeed' => 'Thêm tên miền thành công',
    'delete' => 'Xóa',
    'domain' => 'Tên miền',
    'ip' => 'IP',
    'user_search' => 'Tìm thành viên',
    'user_name' => 'Username',
    'user_regdate' => 'Đăng ký vào',
    'user_regip' => 'IP',
    'user_before' => 'Trước',
    'user_after' => 'Sau',
    'user_add' => 'Thêm thành viên',
    'user_password' => 'Password',
    'user_addsubmit' => 'Submit',
    'user_avatar' => 'Hình đại diện',
    'user_avatar_virtual' => 'Virtual Avatar',
    'user_avatar_real' => 'True picture',
    'delete_avatar' => 'Xóa hình đại diện',
    'delete' => 'Xóa',
    'email' => 'Email',
    'user_list' => 'Danh sách thành viên',
    'user_add_succeed' => 'Thêm thành viên thành công',
    'user_delete_confirm' =>
        'Hành động này không thể khôi phục, bạn có chắc chắn xóa những thành viên này?',
    'user_delete_succeed' => 'Xóa thành công thành viên',
    'user_add_failed' => 'Thêm thành viên thất bại',
    'user_add_username_ignore' => 'Tên thành viên không hợp pháp',
    'user_add_username_badwords' => 'Tên thành viên có bao hàm từ cấm',
    'user_add_username_exists' => 'Tên thành viên đã tồn tại',
    'user_add_email_formatinvalid' => 'Email không cho phép',
    'user_add_email_ignore' => 'Email có đuôi tên miền bị cấm',
    'user_add_email_exists' => 'Email này đã được đăng ký',
    'user_edit_profile' => 'Sửa thành viên',
    'user_edit_profile_sucessfully' => 'Chỉnh sửa thành viên thành công',
    'user_edit_profile_failed' => 'Chỉnh sửa thành viên thất bại',
    'user_keep_blank' => 'Mật khẩu để trống có nghĩa là không đổi',
    'cache_update' => 'Cập nhật cache',
    'cache_update_data' => 'Cập nhật cache dữ liệu',
    'cache_update_tpl' => 'Cập nhật cache giao diện',
    'db_export' => 'Sao lưu dữ liệu',
    'db_export_filename' => 'Tên',
    'db_export_volumesize' => 'Mỗi file có độ lớn(kb)',
    'db_import' => 'Nhập vào',
    'db_list' => 'Ghi chép sao lưu',
    'db_filename' => 'Tên',
    'db_version' => 'Phiên bản',
    'db_dateline' => 'Thời gian',
    'db_size' => 'Độ lớn',
    'db_volume' => 'Vol',
    'db_operation' => 'Thao tác',
    'db_delete_succeed' => 'Bản sao lưu này đã xóa thành công',
    'db_backup_dir' => 'Thư mục sao lưu',
    'db_backup_date' => 'Ngày dự trữ',
    'db_detail' => 'Chi tiết',
    'db_start_delete_dumpfile' =>
        'Bắt đầu xóa sao lưu dữ liệu, xin vui lòng chờ đợi, xin vui lòng không đóng trình duyệt của bạn',
    'db_delete_dumpfile_confirm' =>
        'Tại cùng một thời gian để xóa các cơ sở dữ liệu sao lưu UCenter sẽ bị xóa tất cả các ứng dụng với các thư mục sao lưu, bạn chắc chắn muốn xoá nó?',
    'db_start_import_dumpfile' =>
        'Bắt đầu phục hồi dữ liệu, xin vui lòng chờ đợi, vui lòng không đóng trình duyệt của bạn',
    'db_import_uc_dumpfile_confirm' =>
        'Nhập dữ liệu vào SQL Ucenter, bạn có chăc chắn muốn nhập?',
    'db_import_dumpfile_confirm' =>
        'Nhập dữ liệu vào SQL, bạn có chăc chắn muốn nhập?',
    'db_start_export_dumpfile' =>
        'Bắt đầu back up dữ liệu, xin vui lòng chờ đợi, xin vui lòng không đóng trình duyệt của bạn',
    'db_list_tips' =>
        'Dựa theo ngày tháng của bản sao lưu, nhấn vào "Chi tiết" để vào ứng ứng dụng sao lưu phục hồi',
    'db_import_tips' =>
        'Việc khôi phục lại cần kiểm tra trước, và sau đó nhấp vào "submit"để khôi phục lại dữ liệu sao lưu dự phòng',
    'dumpfile_exists' => 'Bản sao lưu đã tồn tại',
    'message_title' => 'Gợi ý',
    'message_back' => 'Bấm vào đây để trở lại',
    'message_redirect' =>
        'Trang kế tiếp sẽ chạy trong vòng 3 giây nữa, bấm vào đây để bỏ qua...',
    'update_succeed' => 'Cập nhật thành công',
    'log_list' => 'Danh sách nhật ký',
    'log_operator' => 'Người thao tác',
    'log_ip' => 'IP',
    'log_time' => 'Thời gian',
    'log_operation' => 'Thực thi',
    'log_extra' => 'khác ',
    'home_version' => 'Phiên bản UC',
    'home_environment' => 'Phiên bản PHP',
    'home_server_software' => 'Server',
    'home_server_ip' => 'Host name (IP)',
    'home_database' => 'MySQL',
    'home_note_count' => 'Chưa gửi tin',
    'home_pm_count' => 'Số tin nhắn',
    'home_friend_count' => 'Số bạn bè',
    'home_upload_perm' => 'Upload tối đa',
    'home_database_size' => 'Data của diễn đàn',
    'home_attach_size' => 'Data của đính kèm',
    'home_dev' => 'Discuz',
    'home_dev_copyright' => 'Bản quyền thuộc',
    'home_dev_manager' => 'Tổng quản lý',
    'home_dev_team' => 'Nhóm phát triển',
    'home_safe_team' => 'Nhóm bảo mật',
    'home_supported_team' => 'Nhóm hỗ trợ',
    'home_supported_ui' => 'Giao diện',
    'home_supported_thanks' => 'Hỗ trợ phát triển',
    'home_dev_addons' => 'Thiết kế plugin',
    'home_dev_skins' => 'Thiết kế giao diện',
    'home_dev_enterprise_site' => 'Nơi phát hành',
    'home_dev_project_site' => 'Trang web',
    'home_dev_community' => 'Diễn đàn',
    'home_stats' => 'Thống kê',
    'home_member_count' => 'Tổng thành viên',
    'home_app_count' => 'Tổng ứng dụng',
    'home_env' => 'Hệ điều hành',
    'home_envstatus' => '运行环境检测',
    'home_team' => 'Thông tin về mã nguồn',
    'admin_add_succeed' => 'Thêm $addname  làm quản lý',
    'admin_already_is_administrator' => '$addname đã là quản lý',
    'admin_failed' => 'Thêm $addname làm quản lý thất bại',
    'admin_user_nonexistance' => '$addname không tồn tại',
    'admin_config_unwritable' =>
        '/data/cache/config.inc.php không có quyền ghi đè',
    'admin_founder_pw_incorrect' =>
        'Người khởi tạo diễn đàn có mật khẩu sai sót',
    'admin_pw_incorrect' => 'Hai lần nhập mật khẩu không giống',
    'admin_pw_oldpw' => 'Xin vui lòng nhập pass cảu sáng lập viên',
    'admin_pw_newpw' => 'Xin vui lòng nhập một mật khẩu mới',
    'admin_pw_newpw2' => 'Nhập lại mật khẩu',
    'admin_pw_too_short' =>
        'Mật khẩu của bạn là quá ngắn, có thể là không an toàn, bạn chắc chắn bạn thiết lập mật khẩu?',
    'admin_founder_pw_modified' => 'Sửa mật khẩu thành công',
    'admin_add_admin' => 'Thêm quản lý',
    'admin_modify_founder_pw' => 'Sửa mật khẩu',
    'admin_editfoundertips' =>
        '此处密码仅为UCenter后台创始人登陆密码，与各应用管理员密码无关更不会自动同步更改，请务必妥善保存此密码',
    'admin_privilege' => 'Quyền hạn',
    'admin_allow_setting' => 'Thiết lập',
    'admin_allow_app' => 'Ứng dụng',
    'admin_allow_user' => 'Tên thành viên',
    'admin_allow_badwords' => 'Từ cấm',
    'admin_allow_tag' => 'TAG',
    'admin_allow_pm' => 'Tin nhắn',
    'admin_allow_credits' => 'Điểm',
    'admin_allow_hosts' => 'Phân tích tên miền',
    'admin_allow_database' => 'Database',
    'admin_allow_cache' => 'Cache',
    'admin_allow_log' => 'Nhật ký',
    'admin_allow_note' => 'Tin báo',
    'oldpw' => 'Mật khẩu cũ',
    'newpw' => 'Mật khẩu mới',
    'repeatpw' => 'Nhập lại',
    'admin_list' => 'Danh sách quản lý',
    'confirm_delete' => 'Bạn có chắc chắn xóa?',
    'profile' => 'Profile',
    'privilege' => 'Quyền hạn',
    'admin_edit_priv' => 'Sửa quyền hạn quản lý',
    'admin_priv_modified_successfully' =>
        'Chỉnh sửa quyền hạn cho quản lý thành công',
    'admin_priv_modified_failed' => 'Chỉnh sửa quyền hạn cho quản lý thất bại',
    'admin_modification_notice' =>
        'Xin hãy thật thận trọng đối với những quyền: ứng dụng, thành viên, database',
    'admin_allow_pm' => 'Tin nhắn',
    'admin_admin' => 'Quản lý viên',
    'admin_return_admin_ls' => 'Trở lại danh sách quản lý',
    'admin_return_user_ls' => 'Trở lại danh sách thành viên',
    'view_new_version' => 'Xem phiên bản mới nhất',
    'app_allowips' => 'IP cho phép',
    'app_allowips_comment' =>
        'Thiết lập IP đầu cuối để cho phép truy cập vào Ucenter',
    'envstatus_result' => '检测结果',
    'envstatus_ver_too_low' =>
        '您当前系统环境内的 $envstatus[req] 版本 ($envstatus[now_ver]) 过低，程序无法按预期正常运行。我们强烈建议您升级到 $envstatus[sug_ver] 版本，程序正常运行最低要求为 $envstatus[req_ver] 版本。',
    'envstatus_not_found' =>
        '您当前系统环境内未安装或开启 $envstatus[req] 模块，程序无法按预期正常运行。我们强烈建议您安装或开启此模块，以满足程序正常运行的最低要求。',
    'envstatus_ok' =>
        '您当前系统环境适合当前版本的 UCenter $envstatus[version] 。',
);
